import { Content, Inter } from 'next/font/google'
import './globals.css'
import Link from "next/link"
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className={"nav-flex"}>
            <Link href="\">
              home
            </Link>
            <Link href="\posts">
              posts
            </Link>
            <Link href="\articals">
              articals
            </Link>
          </ul>
        </nav>
        {children}</body>
    </html >
  )
}
